apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd        
  annotations:
    # helm install argocd-image-updater argo/argocd-image-updater --namespace argocd でinstallされていることが前提
    argocd-image-updater.argoproj.io/image-list: asia-northeast1-docker.pkg.dev/gcp-iap-test-442622/argocd-app/fastapi-app
    argocd-image-updater.argoproj.io/write-back-method: git       # ArgoCDコントロールプレーンのネームスペースに作成
spec:
  project: default                # デフォルトプロジェクトを使用
  source:
    repoURL: 'https://github.com/izuna385/fastapi-manifests.git'
    targetRevision: HEAD          # Gitのブランチやタグ (ここではデフォルトブランチを使用)
    path: base                    # マニフェストが格納されたパス (本例ではfastapi-manifests/base)
  destination:
    server: https://kubernetes.default.svc
    namespace: default            # アプリをデプロイする対象ネームスペース
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true        # namespaceが未作成でも自動で作成する

---
# ArgoCDサーバーのサービス設定（静的IP + ドメイン対応）
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  type: LoadBalancer
  loadBalancerIP: 104.198.115.185  # Terraformで作成したリージョナル静的IP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server

---
# ArgoCDサーバーの設定（insecureモード + ドメイン設定）
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "true"  # HTTPアクセスを許可

---
# ArgoCDサーバーの設定（ドメイン設定）
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-server-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server-config
    app.kubernetes.io/part-of: argocd
data:
  url: "http://argocd.gke-argocd-terraform-tutorial.com"  # カスタムドメイン
